Event.destroy_all
Profil.destroy_all
User.destroy_all
@user = User.create!( email:"goundor@orange.fr", password:"foobar")
puts"1"
@profil = Profil.create!( nom:"Schweiger", prenom:"Amélie", site:"http://www.lesviesdansent.fr/", activite:"5 rythmes", user: @user)
@profil.pseudo = @profil.prenom.capitalize + " " + @profil.nom.first.capitalize + " . "
@profil.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   9   ,   11  ,   15  ,   0   ), fin: DateTime.new(   2016    ,   9   ,   11  ,   17  ,   0   ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   9   ,   18  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   9   ,   18  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   10  ,   25  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   10  ,   25  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   0" , ville:"    0" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   10  ,   2   ,   11  ,   30  ), fin: DateTime.new(   2016    ,   10  ,   2   ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   10  ,   16  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   10  ,   16  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   10  ,   23  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   10  ,   23  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   0" , ville:"    0" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   10  ,   30  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   10  ,   30  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   0" , ville:"    0" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   11  ,   13  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   11  ,   13  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   11  ,   27  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   11  ,   27  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   12  ,   4   ,   11  ,   30  ), fin: DateTime.new(   2016    ,   12  ,   4   ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75011" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   12  ,   18  ,   11  ,   30  ), fin: DateTime.new(   2016    ,   12  ,   18  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75012" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   1   ,   8   ,   11  ,   30  ), fin: DateTime.new(   2017    ,   1   ,   8   ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75013" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   1   ,   15  ,   15  ,   0   ), fin: DateTime.new(   2017    ,   1   ,   15  ,   17  ,   0   ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75014" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   1   ,   29  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   1   ,   29  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75015" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   2   ,   12  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   2   ,   12  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75016" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   2   ,   19  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   2   ,   19  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75017" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   2   ,   26  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   2   ,   26  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75018" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   3   ,   12  ,   15  ,   0   ), fin: DateTime.new(   2017    ,   3   ,   12  ,   17  ,   0   ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75019" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   3   ,   19  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   3   ,   19  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75020" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   3   ,   26  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   3   ,   26  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75021" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   4   ,   9   ,   11  ,   30  ), fin: DateTime.new(   2017    ,   4   ,   9   ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75022" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   4   ,   23  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   4   ,   23  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75023" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   4   ,   30  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   4   ,   30  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75024" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   5   ,   7   ,   15  ,   0   ), fin: DateTime.new(   2017    ,   5   ,   7   ,   17  ,   0   ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75025" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   5   ,   14  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   5   ,   14  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75026" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   5   ,   28  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   5   ,   28  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75027" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   6   ,   11  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   6   ,   11  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75028" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   6   ,   18  ,   11  ,   30  ), fin: DateTime.new(   2017    ,   6   ,   18  ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75029" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2017    ,   7   ,   2   ,   11  ,   30  ), fin: DateTime.new(   2017    ,   7   ,   2   ,   13  ,   30  ), prix:    18  , lieu:"   Studio One Step" , adresse:"  18-20 rue du faubourg du Temple" , cp:"   75030" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° République" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   9   ,   20  ,   19  ,   30  ), fin: DateTime.new(   2016    ,   9   ,   20  ,   21  ,   30  ), prix:    18  , lieu:"   Micadanses - Studio May B" , adresse:"  15, rue Geoffroy L'Asnier" , cp:"   75004" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° St Paul" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   10  ,   18  ,   19  ,   30  ), fin: DateTime.new(   2016    ,   10  ,   18  ,   21  ,   30  ), prix:    18  , lieu:"   Micadanses - Studio May B" , adresse:"  15, rue Geoffroy L'Asnier" , cp:"   75004" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° St Paul" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   11  ,   22  ,   19  ,   30  ), fin: DateTime.new(   2016    ,   11  ,   22  ,   21  ,   30  ), prix:    18  , lieu:"   Micadanses - Studio May B" , adresse:"  15, rue Geoffroy L'Asnier" , cp:"   75004" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° St Paul" , user: @user)    ; @evt.set_seach ; @evt.save
@evt = Event.new( titre:"Danser la vague des 5 Rythmes", description:"Cours de rythmes", debut: DateTime.new(    2016    ,   12  ,   13  ,   19  ,   30  ), fin: DateTime.new(   2016    ,   12  ,   13  ,   21  ,   30  ), prix:    18  , lieu:"   Micadanses - Studio May B" , adresse:"  15, rue Geoffroy L'Asnier" , cp:"   75004" , ville:"    Paris" , pays:" France », reduit:"         15" , transport:"    M° St Paul" , user: @user)    ; @evt.set_seach ; @evt.save

puts"2"
