@user = User.create!( email: "goundor@orange.fr", password: "foobar")
puts "1"
@profil = Profil.create!( nom: "Schweiger", prenom: "Amélie", site: "http://www.lesviesdansent.fr/", activite: "5 rythmes", user: @user)
@profil.pseudo = @profil.prenom.capitalize + " " +@profil.nom.first.capitalize + "  . "
@profil.save
puts "2"
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 9, 11, 15, 0 ), fin: DateTime( 2016, 9, 11, 17, 0 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 9, 18, 11, 30 ), fin: DateTime( 2016, 9, 12, 18, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 10, 25, 11, 30 ), fin: DateTime( 2017, 10, 13, 19, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  0 "  , ville: "  0 "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 10, 2, 11, 30 ), fin: DateTime( 2016, 10, 14, 20, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 10, 16, 11, 30 ), fin: DateTime( 2016, 10, 15, 21, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 10, 23, 11, 30 ), fin: DateTime( 2016, 10, 16, 22, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  0 "  , ville: "  0 "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 10, 30, 11, 30 ), fin: DateTime( 2016, 10, 17, 23, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  0 "  , ville: "  0 "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 11, 13, 11, 30 ), fin: DateTime( 2016, 11, 18, 24, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 11, 27, 11, 30 ), fin: DateTime( 2016, 11, 19, 25, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 12, 4, 11, 30 ), fin: DateTime( 2016, 12, 20, 26, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75011 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 12, 18, 11, 30 ), fin: DateTime( 2016, 12, 21, 27, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75012 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 1, 8, 11, 30 ), fin: DateTime( 2017, 1, 22, 28, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75013 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 1, 15, 15, 0 ), fin: DateTime( 2017, 1, 23, 29, 0 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75014 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 1, 29, 11, 30 ), fin: DateTime( 2017, 1, 24, 30, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75015 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 2, 12, 11, 30 ), fin: DateTime( 2017, 2, 25, 31, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75016 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 2, 19, 11, 30 ), fin: DateTime( 2017, 2, 26, 32, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75017 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 2, 26, 11, 30 ), fin: DateTime( 2017, 2, 27, 33, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75018 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 3, 12, 15, 0 ), fin: DateTime( 2017, 3, 28, 34, 0 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75019 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 3, 19, 11, 30 ), fin: DateTime( 2017, 3, 29, 35, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75020 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 3, 26, 11, 30 ), fin: DateTime( 2017, 3, 30, 36, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75021 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 4, 9, 11, 30 ), fin: DateTime( 2017, 4, 31, 37, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75022 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 4, 23, 11, 30 ), fin: DateTime( 2017, 4, 32, 38, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75023 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 4, 30, 11, 30 ), fin: DateTime( 2017, 4, 33, 39, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75024 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 5, 7, 15, 0 ), fin: DateTime( 2017, 5, 34, 40, 0 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75025 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 5, 14, 11, 30 ), fin: DateTime( 2017, 5, 35, 41, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75026 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 5, 28, 11, 30 ), fin: DateTime( 2017, 5, 36, 42, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75027 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 6, 11, 11, 30 ), fin: DateTime( 2017, 6, 37, 43, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75028 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 6, 18, 11, 30 ), fin: DateTime( 2017, 6, 38, 44, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75029 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2017, 7, 2, 11, 30 ), fin: DateTime( 2017, 7, 39, 45, 30 ), prix: 18, lieu: "  Studio One Step "  , adresse: "  18-20 rue du faubourg du Temple "  , cp: "  75030 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° République "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 9, 20, 19, 30 ), fin: DateTime( 2016, 9, 40, 46, 30 ), prix: 18, lieu: "  Micadanses - Studio May B "  , adresse: "  15, rue Geoffroy L'Asnier "  , cp: "  75004 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° St Paul "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 10, 18, 19, 30 ), fin: DateTime( 2016, 10, 41, 47, 30 ), prix: 18, lieu: "  Micadanses - Studio May B "  , adresse: "  15, rue Geoffroy L'Asnier "  , cp: "  75004 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° St Paul "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 11, 22, 19, 30 ), fin: DateTime( 2016, 11, 42, 48, 30 ), prix: 18, lieu: "  Micadanses - Studio May B "  , adresse: "  15, rue Geoffroy L'Asnier "  , cp: "  75004 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° St Paul "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 2016, 12, 13, 19, 30 ), fin: DateTime( 2016, 12, 43, 49, 30 ), prix: 18, lieu: "  Micadanses - Studio May B "  , adresse: "  15, rue Geoffroy L'Asnier "  , cp: "  75004 "  , ville: "  Paris "  , pays: " France ", reduit: "  15 "  , transport: "  M° St Paul "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 0, 0, 0, 0, 0 ), fin: DateTime( 0, 0, 44, 50, 0 ), prix: 0, lieu: "  0 "  , adresse: "  0 "  , cp: "  0 "  , ville: "  0 "  , pays: " France ", reduit: "  0 "  , transport: "  0 "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 0, 0, 0, 0, 0 ), fin: DateTime( 0, 0, 45, 51, 0 ), prix: 0, lieu: "  0 "  , adresse: "  0 "  , cp: "  0 "  , ville: "  0 "  , pays: " France ", reduit: "  0 "  , transport: "  0 "  , user: @user) ; @evt.set_seach ; @evt.save
@evt = Event.new( titre: "Danser la vague des 5 Rythmes", description: "Cours de rythmes", debut: DateTime( 0, 0, 0, 0, 0 ), fin: DateTime( 0, 0, 46, 52, 0 ), prix: 0, lieu: "  0 "  , adresse: "  0 "  , cp: "  0 "  , ville: "  0 "  , pays: " France ", reduit: "  0 "  , transport: "  0 "  , user: @user) ; @evt.set_seach ; @evt.save
puts "3"
